### ISSUE TITLE
Unwanted full stop

### ISSUE THREAD

**Issue by nigelhorne** [benkasminbullock/Lingua-EN-ABC#5]
```
$ cat foo
#!/usr/bin/env perl

use Lingua::EN::ABC;

my $string = 'Mr. and Mrs. Smith';

print Lingua::EN::ABC::b2a($string), "\n";
$ perl foo
Mr.. and Mrs. Smith
```

**Comment by benkasminbullock** [comment]
On Wed, 12 Sep 2018 at 22:09, Nigel Horne <notifications@github.com> wrote:

> $ cat foo
> #!/usr/bin/env perl
>
> use Lingua::EN::ABC;
>
> my $string = 'Mr. and Mrs. Smith';
>
> print Lingua::EN::ABC::b2a($string), "\n";
> $ perl foo
> Mr.. and Mrs. Smith
>
> Thanks for finding this. The naive method used to alter punctuation
between British and American seems to have failed here. I've removed the
entries for Mr. and Dr. in this commit:

commit d0f7242ad72d6b36aba1df826a51659d6d97cd9c (HEAD -> master)
Author: Ben Bullock <benkasminbullock@gmail.com>
Date:   Thu Sep 13 08:35:13 2018 +0900

    Remove Mr. / Dr. entries

    The Mr. and Dr. replacements give errors when the British text
    contains Mr. already.

I'll think about ways to fix punctuation issues more correctly for a future
release.

Thank you again.



>

**Comment by benkasminbullock** [comment]
This is done in the latest release so I'm marking as closed. Please re-open this issue if you're not satisfied about this.
