### ISSUE TITLE
lorry is missing

### ISSUE THREAD

**Issue by nigelhorne** [benkasminbullock/Lingua-EN-ABC#6]
Please add:

British: lorry
American: truck

**Comment by benkasminbullock** [comment]
Thank you for this addition. It is done here:

ommit 4500e7f049db445d1310362f0148f7aa453a820e (HEAD -> master, origin/master)
Author: Ben Bullock <benkasminbullock@gmail.com>
Date:   Sat Nov 30 11:35:46 2019 +0900

    Add lorry/truck (thanks to Nigel Horne)

**Comment by nigelhorne** [comment]
It still seems to be the case, are we awaiting a new release?  This was fixed a couple of years ago.

**Comment by benkasminbullock** [comment]
Thank you for the report.

I've uploaded a new version, 0.11, to CPAN.

**Comment by nigelhorne** [comment]
Thanks. 

-Nigel
